name: Android Problem Matcher
description: Add problem matchers for Android development (Gradle)
inputs:
  matchers:
    default: 'kotlin_gradle,android_lint_gradle,junit_gradle'
    required: false
    description: 'A comma separated list of problem matcher identifiers'
  exclude:
    default: 'false'
    required: false
    description: 'Specify true if you would like to use the *matchers* to exclude'
runs:
  using: node16
  main: index.js
branding:
  color: red
  icon: flag
